-- =============================================
-- Sheria Smart Database Setup - Step 3: Expand Document Types
-- Run this after 02_document_requests.sql
-- =============================================

-- AlterTable: Add all new document types to enum
ALTER TABLE `document_requests` MODIFY `documentType` ENUM(
    'EMPLOYMENT_CONTRACT',
    'SERVICE_AGREEMENT', 
    'LEASE_AGREEMENT',
    'SALES_PURCHASE_AGREEMENT',
    'DISTRIBUTION_AGREEMENT',
    'PARTNERSHIP_AGREEMENT',
    'ENHANCED_EMPLOYMENT_CONTRACT',
    'INDEPENDENT_CONTRACTOR_AGREEMENT',
    'NON_COMPETE_AGREEMENT',
    'ENHANCED_LEASE_AGREEMENT',
    'SALE_OF_LAND_AGREEMENT',
    'PROPERTY_MANAGEMENT_AGREEMENT',
    'PRENUPTIAL_AGREEMENT',
    'POSTNUPTIAL_AGREEMENT',
    'CHILD_CUSTODY_SUPPORT_AGREEMENT',
    'COPYRIGHT_ASSIGNMENT_AGREEMENT',
    'TRADEMARK_LICENSE_AGREEMENT',
    'PATENT_LICENSING_AGREEMENT',
    'ARTICLES_OF_ASSOCIATION',
    'SHAREHOLDER_AGREEMENT',
    'BOARD_RESOLUTION',
    'SETTLEMENT_AGREEMENT',
    'ARBITRATION_AGREEMENT',
    'MEDIATION_AGREEMENT',
    'DATA_PROTECTION_COMPLIANCE_AGREEMENT',
    'ANTI_MONEY_LAUNDERING_COMPLIANCE',
    'ENVIRONMENTAL_COMPLIANCE_AGREEMENT'
) NOT NULL;