deployment:
  tasks:
    # FRONTEND
    - export FRONTEND_PATH=/home2/robertki/sheria.robertkibet.com
    - cd frontend
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build
    - /usr/local/bin/npm run export
    - /bin/rsync -av out/ $FRONTEND_PATH

    # BACKEND
    - cd ../backend
    - /usr/local/bin/npm install
    # Build
    - /usr/local/bin/npm run build || true
    # Restart
    - touch tmp/restart.txt || true
