-- AlterTable
ALTER TABLE `document_requests` ADD COLUMN `emailError` TEXT NULL,
    ADD COLUMN `emailRetryCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `lastEmailAttempt` DATETIME(3) NULL,
    MODIFY `status` ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'EMAIL_QUEUED', 'EMAIL_SENT') NOT NULL DEFAULT 'PENDING';
